Api Refactor
Navi-Cloud/Navi-Server pull request #19
Opened 2021-03-07 14:54 UTC by 0JIEUN0

File Api Refactor

2021-03-07 15:02 UTC, 0JIEUN0 commented
생각해볼 것:
1. FileIOException 이 발생했을 때 HttpStatus.INTERNAL_SERVER_ERROR 를 status code 로 반환하면 될지?
-> 서버에서 파일을 작성하는데 (업로드 할 때) 오류가 나는 경우. 500 이 맞을지.

2. FileDownload ) 파일 다운 service 에서 pair 를 반환하는데 api 에서 각각의 Exception 을 어떻게 헨들링해줄것인가..
기본적으론 pair 가 null 이면 Not Found 인 것인데,, (지금 그렇게 처리하고 있음)
이 외에도 Server Error [5xx] 이 발생할수도 있음. 이건 어떻게 처리해줄것인가!

2021-03-11 07:12 UTC, KangDroid commented on src/main/kotlin/com/navi/server/service/FileService.kt
> +        try{
가능 하다면, runCatching구문으로 슬슬 바꿔 보는 것도 좋을 것 같습니다.
[전체 피드백 내용 참고해주세요/]

2021-03-11 07:13 UTC, KangDroid commented on src/main/kotlin/com/navi/server/service/FileService.kt
> +        } catch (e: EmptyResultDataAccessException) {
위 커멘트와 동일하고, 가능하면 Exception이 날 수 있는 부분만 Try-Catch/runCatching구문을 작성해주세요.
모든 부분을 감싸면 어느 코드에서 Exception이 일어날 수 있는지 잘 모를거 같습니다 ㅠㅠ

2021-03-11 07:14 UTC, KangDroid commented on src/main/kotlin/com/navi/server/service/FileService.kt
>      fun fileDownload(token: String) : Pair<FileResponseDTO, Resource>? {
차라리 API컨트롤러에서 핸들링하는 코드를  서비스 로직의 fileDownload 함수에 넣어서, fileDownload 자체가 responseentity를 반환하게 하는게 좋을 것 같습니다.
만약 서비스 로직에서 Exception이 발생한다면, 그대로 Exception Controller에 넘어 갈테니까요

2021-03-11 07:15 UTC, KangDroid requested changes
변경사항
- FileService.fileUpload()
    - 여기서 전체 구문을 try-catch문으로 감쌌는데
        - 각 Exception을 Throw하는 코드 “만” Try-Catch구문을 작성하면 좋을 것 같습니다. 
        - 가능하다면, Java의 Try-Catch문 보다는, Kotlin 형식의 runcatching -> onFailure/onSuccess/getOrNull을 복합적으로 활용하는게 좋다고 생각됩니다.
            - runCatching 구문에서 .onFailure 람다함수의 인풋은 Throwable 객체입니다.
            - 대부분의 Exception 클래스들은 Throwable을 동시 상속하기 때문에, 
            - it를 인자라고 한다면, if (it.cause is ~~Exception)으로 판별하거나, 하나의 runCatching 구문에서 여러개의 Exception을 부득이하게 처리해야되는 경우 when을 같이 쓰시면 좋을 것 같습니다.
    - 현재 FileIOException에 대한 답변입니다.
        - FileIOException은 느낌 상 105번째 줄의 File객체 생성 중 나올 수 있다고 판단되는데, 이 부분은 그냥 500 Internal Server Error로 처리해도 될 듯 합니다.\
- FileService.fileDownload()
    - 지금 코드를 보아 하니, 서비스 로직에서 페어를 가지고 오고, 페어를 잘 감싸서 ResponseEntity로 주는 형태인데, fileDownload시 여러 에러를 처리하려면, 그냥 서비스 로직에다가 모든 코드를 넣고 FileApiController.fileDownload()에서는 단순히 return fileService.fileDownload(token) 형식으로만 짜도 괜찮아 보입니다.

2021-03-12 07:39 UTC, KangDroid approved these changes

2021-03-12 07:39 UTC, merged